---
# Build a local SSH configuration. Specifically, we create a file ~/.ssh/ansible_created_config
# which we include into ~/.ssh/config. In this file, we add one entry for each host

- name: Cleanup SSH config file
  shell: "echo > ~/.ssh/ansible_created_config"
  # For each host, we also add an entry to .ssh/ansible_created_config
- name: Add host to SSH config file
  shell: |
    cat >> ~/.ssh/ansible_created_config <<EOF
    Host *
      StrictHostKeyChecking no
      UserKnownHostsFile=/dev/null
    EOF
  loop: "{{ hostvars | dict2items  }}"
  loop_control:
    label: "{{item.key}}"
  when: item.key != "localhost"

- name: remove kube from known hosts
  command: ssh-keygen -f ~/.ssh/known_hosts -R {{ item.value.ansible_ssh_host }}
  loop: "{{ hostvars | dict2items  }}"
  loop_control:
    label: "{{item.key}}"
  when: item.key != "localhost"

- name: add kubeserver to known host
  command: ssh-keyscan -t rsa {{ item.value.ansible_ssh_host }} >> ~/.ssh/known_hosts
  loop: "{{ hostvars | dict2items  }}"
  loop_control:
    label: "{{item.key}}"
  when: item.key != "localhost"

- name: Include our file in main config file
  lineinfile:
    create: yes
    state: present
    path: ~/.ssh/config
    line: Include ~/.ssh/ansible_created_config