- name: Create S3 Bucket for State Store
  amazon.aws.s3_bucket:
    name: {{ bucket_name }}
    region: {{ aws_region }}
    state: present
    versioning: true
    # tags:
    #   Name: "dr-drill-state-store"
