variable "project_name" {}
variable "public_subnet_az1_id" {}
variable "public_subnet_az2_id" {}
variable "public_subnet_az3_id" {}
variable "internet_gateway" {}
variable "vpc_id" {}
variable "private_subnet_az1_id" {}
variable "private_subnet_az2_id" {}
variable "private_subnet_az3_id" {}
variable "rds_public_subnet_az1_id" {}
variable "rds_public_subnet_az2_id" {}
variable "rds_public_subnet_az3_id" {}
variable "rds_private_subnet_az1_id" {}
variable "rds_private_subnet_az2_id" {}
variable "rds_private_subnet_az3_id" {}