---
# tasks file for roles/configk8sctl
- name: Update APT cache
  apt:
    update_cache: yes
  retries: 5
  delay: 5

# - name: install required packages
#   apt:
#     pkg:
#     - apt-transport-https
#     # - gnupg2
#     - python3-pip
#     - git
#     # - pip
#     # - libpq-dev
#     # - nginx
#   # until: apt_status is success
#   # delay: 6
#   # retries: 10

- name: Install required packages
  apt:
    pkg:
      - apt-transport-https
      - python3-pip
      - git
    state: present

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
