- name: create following dirs 
  file:
    path: "{{item}}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  loop:
    - ~/.kube/
    - ~/.aws/

- name: copy kubeconfig 
  copy:
    src: ./kubeconfig.yml
    dest: ~/.kube/config

- name: copy aws 
  copy:
    src: ~/.aws/credentials
    dest: ~/.aws/credentials

- name: copy aws auth config
  copy: 
    src: ./kube_auth_file.yml
    dest: /tmp/

- name: run aws auth
  command: kubectl apply -f /tmp/kube_auth_file.yml